spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # Use a file-based H2 database so that data persists between restarts
    url: jdbc:h2:file:./data/notificationdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8084