spring:
  application:
    name: notification-service
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: crusher3846@gmail.com
    password: evvr fecj znyv hlwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

config:
  import: "optional:file:./config/application-secrets.yml"

logging:
  level:
    org.springframework.security: DEBUG
