networks:
  ecommerce-network:

services:
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    networks:
      - ecommerce-network

  config-server:
    image: config-server:latest
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
    networks:
      - ecommerce-network

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    networks:
      - ecommerce-network


  product-service:
    image: product-service:latest
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    networks:
      - ecommerce-network

  cart-service:
    image: cart-service:latest
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    networks:
      - ecommerce-network

  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    networks:
      - ecommerce-network


  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    networks:
      - ecommerce-network