server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            # You can add more routes here for other services (e.g., product-service, order-service)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
