spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
server:
  port: 8080

# Eureka configuration so that the gateway can register and discover services
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/