#server:
#  port: 8081
spring:
  application:
    name: user-service
  profiles:
    active: dev
#  cloud:
#    config:
#      enabled: false
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#logging:
#  level:
#    org.springframework.cloud.config: DEBUG


