spring:
  application:
    name: user-service
#  cloud:
#    config:
#      enabled: true
#      uri: configserver
  profiles:
    active: dev
#  config:
#    import: configserver # Imports configuration from the Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


