spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

#logging:
#  level:
#    root: INFO
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
